const dataInit = {
  status: 'success',
  message: 'Data keluhan berhasil ditemukan',
  all: [
    {
      Nama: 'Semua POP',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
      Semua_RFO_Keluhan: 0,
      Semua_RFO_Gangguan: 0,
    },
    {
      Nama: 'Yogyakarta',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
    {
      Nama: 'Surakarta',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
    {
      Nama: 'Purwokerto',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
  ],
  today: [
    {
      Nama: 'Semua POP',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
      Semua_RFO_Keluhan: 0,
      Semua_RFO_Gangguan: 0,
    },
    {
      Nama: 'Yogyakarta',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
    {
      Nama: 'Surakarta',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
    {
      Nama: 'Purwokerto',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
  ],
  yesterday: [
    {
      Nama: 'Semua POP',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
      Semua_RFO_Keluhan: 0,
      Semua_RFO_Gangguan: 0,
    },
    {
      Nama: 'Yogyakarta',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
    {
      Nama: 'Surakarta',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
    {
      Nama: 'Purwokerto',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
  ],
  a_week_ago: [
    {
      Nama: 'Semua POP',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
      Semua_RFO_Keluhan: 0,
      Semua_RFO_Gangguan: 0,
    },
    {
      Nama: 'Yogyakarta',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
    {
      Nama: 'Surakarta',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
    {
      Nama: 'Purwokerto',
      Semua_Keluhan: 0,
      Semua_Keluhan_Closed: 0,
      Semua_Keluhan_Open: 0,
    },
  ],
  this_month: [
    {
      Nama: 'Semua Keluhan Sebulan',
      Total: 0,
    },
    {
      Nama: 'Semua Keluhan Sebulan Yogyakarta',
      Total: 0,
    },
    {
      Nama: 'Semua Keluhan Sebulan Surakarta',
      Total: 0,
    },
    {
      Nama: 'Semua Keluhan Sebulan Purwokerto',
      Total: 0,
    },
    {
      Nama: 'Semua RFO Keluhan Sebulan',
      Total: 0,
    },
    {
      Nama: 'Semua RFO Gangguan Sebulan',
      Total: 0,
    },
  ],
  this_year: [
    {
      Nama: 'Januari',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'Februari',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'Maret',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'April',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'April',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'Juni',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'Juli',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'Agustus',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'September',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'Oktober',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'November',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
    {
      Nama: 'Desember',
      'Semua POP': 0,
      Yogyakarta: 0,
      Surakarta: 0,
      Purwokerto: 0,
    },
  ],
};

export default dataInit;
